### ISSUE TITLE
BUFR Station ID needs to be translated to ACDD (MQTT)

### ISSUE THREAD

**Issue by istvans-mn** [EURODEO/e-soh-event-queue#11]
There are few different examples in the bufr branch.  
Extensions:
- buf[r] : bufr file
- txt : bufr text dump, fomat:  [ Desciptor ]  Value Unit Name
- json : mqtt message(s) 

Need to check the properties: station_id, ... etc

The different station_id, wmo_block and other variables need be mapped to a station_id variable in the MQTT spec

**Comment by istvans-mn** [comment]
There are two CF values: platform_id, platform_name

Options:
1. Create a concatenated platform_id from source data, for example:
platform_id = "48:976:::::"
where: 48 wmo_block_number, 976 wmo_station_number, the following fields: wigos_is, oscar_id, state_id, national_station_id, buoy_id, aircraft... , the missing fields are empty/filled from Oscar.
platform_name = "VARIN"
or:
platform_id = "::::633:96980:"
platform_name = "KORGASEN"

2. Create object:
        "esoh_platform_id": {
            "wmo_block_number": 48,
            "wmo_station_number": 976,
            "station_or_site_name": "VARIN"
        }
        "esoh_platform_id": {
            "state_identifier": "NORWAY",
            "national_station_number": 96890,
            "station_or_site_name": "KORGAASEN"
        }

3. Create uniq internal_id:
platform_id = "1561637862374619"

4. Drop the platform_id

**Comment by mortenwh** [comment]
We should be careful creating new internal "systems" like internal ids. Can we use just the WIGOS ID? So, something like:

- ACDD platform = WIGOS ID
- ACDD platform_vocabulary = WIGOS (should be a url)

**Comment by istvans-mn** [comment]
We can generate WIGOS ID following the attached document. Page 9,14

[WIGOS-IDs_Webinar_03Dec2018_v2.pptx](https://github.com/EURODEO/e-soh-event-queue/files/12657500/WIGOS-IDs_Webinar_03Dec2018_v2.pptx)

**Comment by mortenwh** [comment]
Platform WIGOS ID added, if available. Try to get WIGOS ID from Oscar. Otherwise, just "Not available" as value to ACDD platform attribute.
