### ISSUE TITLE
Update required fields in mqtt message. 

### ISSUE THREAD

**Issue by Teddy-1000** [EURODEO/e-soh-event-queue#16]
Currently there are some shortcomings in the mandatory fields in the mqtt message spec. This should be updated to secure sufficient data and metadata will be embedded in the message for ingestion and rediscovery in the datastore.

**Comment by Teddy-1000** [comment]
If we are going to publish message notification about datasets being available, the message specification should be updated with fields identifying the type of message. There is a root level field called "type" that is currently unused that could be used for this purpose. The usage for this field is not well documented in [WIS2](https://community.wmo.int/en/wis2-messages).

**Comment by johtoblan** [comment]
We need to add station_identification from #11 maybe.
